### ISSUE TITLE
Support Custom LogGroupName

### ISSUE THREAD

**Issue by vincentclee** [dougmoscrop/serverless-plugin-log-subscription#19]
Currently, the `LogGroupName` is generated dynamically. 

**AWS Docs**
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-subscriptionfilter.html#cfn-cwl-subscriptionfilter-loggroupname

**Proposed config**

```
custom:
  logSubscription:
    destinationArn: 'some-arn'
    roleArn: 'some-arn'
    logGroupName: 'some-log-group-name'
```

**Comment by et304383** [comment]
Why would you need this?  Serverless itself takes care of the log group and its name, which you can't control.  This is only creating a filter on that group and forwarding logs to a destination ARN.

**Comment by dougmoscrop** [comment]
I agree with @et304383 this doesn't quite make sense to me.

Maybe what you would like is something like

```yml
custom:
  logSubscription:
    destinationArn: 'some-arn'
    roleArn: 'some-arn'
    logGroups:
      -'some-log-group-name'
```

Where these are *additional* log groups you subscribe to.  They would not be created, but this is like "oh, I have this other log group that I'd also like to subscribe to"

If so, PRs welcome and I may have use for this myself but not sure if I will be working on it anytime soon.
