### ISSUE TITLE
Support for SLS v3?

### ISSUE THREAD

**Issue by bondezbond** [dougmoscrop/serverless-plugin-log-subscription#25]
I noticed this warning when upgrading a project from 1.x -> 2.35.

```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "custom.logSubscription.destinationArn": Value not found at "self" source
            From a next major this will be communicated with a thrown error.
```

So when v3.0 is released this would break. Is there plans on work on it before that major release?

**Comment by dougmoscrop** [comment]
In this case I believe it is a problem with your project configuration, not this plugin.  You're referring to something `${self:....}` and it's not defined.

**Comment by bondezbond** [comment]
So the project is quite simple. We don't reference this specific value anywhere else in the project. I've created a sample project to show the errors. https://github.com/bondezbond/sls-plugin-log.

**Comment by dougmoscrop** [comment]
You're right that the handling changed from v1 to v2, but I still don't think it has anything to do with this plugin.

```bash
$ npx serverless package
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "custom.logSubscription.destinationArn": Value not found at "env" source,
              - Cannot resolve variable at "resources.Resources.Role.Properties.RoleName": Value not found at "self" source
```

```bash
$ CW_LOG_ARN=foo npx serverless package
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "resources.Resources.Role.Properties.RoleName": Value not found at "self" source
```

You can see how the "desitnationArn" warning goes away, because I defined the variable.

But your original post refers to "self" source not "env" source, so your repo example isn't 1:1, but it's still related to your project configuration, not this plugin.  The easiest way to demonstrate this is remove "- serverless-plugin-log-subscription" from the plugins section:

The warning persists, because it is an issue with how you are defining your variables.

**Comment by bondezbond** [comment]
The values interpreted are all self defined in serverless.yaml. Its constructing the value for `destinationArn:` based on which environment its being deployed too. For example

```
custom:
  logSubscription:
    enabled: true
    destinationArn: arn:aws:logs:${self:provider.region}:11111111:destination:${self:custom.environment.${self:provider.stage}.accountAlias}-cloudwatch-lambda-destination-${self:provider.region}
  environment:
    dev:
      accountAlias: awsdev
  prune:
    automatic: true
    number: 3
```
