### ISSUE TITLE
The final policy size is bigger than the limit

### ISSUE THREAD

**Issue by amoghesturi** [dougmoscrop/serverless-plugin-log-subscription#40]
I am using the following configuration and receiving error

```
custom:
  configFile: ${file(./config/${self:provider.stage}.yml)}
  stage: ${opt:stage, self:provider.stage}
  domains:
    production: ${self:custom.configFile.DOMAIN}
    development: ${self:custom.configFile.DOMAIN}
    qa: ${self:custom.configFile.DOMAIN}
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: dummyPath
    createRoute53Record: true
    endpointType: 'regional'
    stage: ${self:provider.stage}
  serverless-layers:
    - common:
        layersDeploymentBucket: 'platform-${self:provider.stage}-${self:provider.region}'
        dependenciesPath: ./package.json
        compatibleRuntimes: ["nodejs14.x"]
  region: ${self:custom.configFile.REGION, 'ap-south-1'}
  logSubscription:
    enabled: ${self:custom.configFile.LOG_AGGREGATION, true}
    destinationArn: ${self:custom.configFile.LOG_STREAM} // Pointing to 

provider:
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::#{AWS::AccountId}:policy/platform_${self:provider.stage}
        - arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
  deploymentBucket:
    name: com.serverless.${self:provider.stage}.${self:provider.region}.deploys
```

We have more than 15 rest API functions deployed through this and we are receiving the following error 

An error occurred: FunctionNameLogLambdaPermission - The final policy size (20798) is bigger than the limit (20480). (Service: AWSLambda; Status Code: 400; Error Code: PolicyLengthExceededException; Request ID: <>; Proxy: null).

**Comment by paolo-rechia** [comment]
Hi, we had a similar problem. We deployed dozens of stacks and then this error started showing up.

The reason why is that this plugin creates policies like the following:
```json
{
  "Version": "2012-10-17",
  "Id": "default",
  "Statement": [
    {
      "Sid": "function1-YYYYYY",
      "Effect": "Allow",
      "Principal": {
        "Service": "logs.eu-central-1.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:eu-central-1:XXXXXXXX:function:function1",
      "Condition": {
        "ArnLike": {
          "AWS:SourceArn": "arn:aws:logs:eu-central-1:XXXXXXXX:log-group:/aws/lambda/function1:*"
        }
      }
    },
    {
      "Sid": "function2-ZZZZZZZ",
      "Effect": "Allow",
      "Principal": {
        "Service": "logs.eu-central-1.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:eu-central-1:XXXXXXXX:function:function2",
      "Condition": {
        "ArnLike": {
          "AWS:SourceArn": "arn:aws:logs:eu-central-1:XXXXXXXX:log-group:/aws/lambda/function2:*"
        }
      }
    }
  ]
}
```

As you can see, it's one statement generated per lambda function. This quickly fills up your log subscription policy size limit.
To work around this, we rolled this policy in the log subscription lambda:

```json
      "Condition": {
        "ArnLike": {
          "AWS:SourceArn": "arn:aws:logs:eu-central-1:XXXXXXXX:log-group:/aws/lambda/*:*"
         }
       }
```
And then disabled the auto generated permissions with the flag `addLambdaPermission` set to `false`
```yml
  logSubscription:
    enabled: true
    destinationArn: your-destination-arn
    addLambdaPermission: false
```

I hope this helps you.
