### ISSUE TITLE
Enable Api Gateway subscriptions for only the execution logs

### ISSUE THREAD

**Issue by GoGoris** [dougmoscrop/serverless-plugin-log-subscription#43]
Using the Api Gateway logsubscription support with only execution logging enabled fails with the error "Unresolved resource dependencies [ApiGatewayLogGroup] in the Resources block of the template" because serverless creates this logGroup conditionally based on logs.restApi.accessLogging. 

To reproduce add the following config in your serverless.yml:
```yaml
 logs:
    restApi:
      executionLogging: true
      accessLogging: false
```

The reverse problem probably exists as well when accessLogging is enabled without executionLogging.
