### ISSUE TITLE
json-cycle $ref issues

### ISSUE THREAD

**Issue by dougmoscrop** [dougmoscrop/serverless-plugin-log-subscription#5]
as per @rkdavidson in https://github.com/dougmoscrop/serverless-plugin-split-stacks/issues/41

```yml
service: aws-nodejs

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  # - serverless-plugin-split-stacks
  - serverless-plugin-log-subscription

custom:
  logSubscription:
    enabled: true
    destinationArn:
      Fn::Join:
        - ':'
        - - 'arn:aws:kinesis:us-west-2'
          - Ref: 'AWS::AccountId'
          - 'asdf'
    roleArn:
      Fn::Join:
        - ':'
        - - 'arn:aws:iam:'
          - Ref: 'AWS::AccountId'
          - 'role/asdf'

functions:
  hello:
    handler: handler.hello
  goodbye:
    handler: handler.goodbye
```

produces:

```json
"GoodbyeSubscriptionFilter": {
      "Type": "AWS::Logs::SubscriptionFilter",
      "Properties": {
        "DestinationArn": {
          "$ref": "$[\"Resources\"][\"HelloSubscriptionFilter\"][\"Properties\"][\"DestinationArn\"]"
        },
        "FilterPattern": "",
        "LogGroupName": "/aws/lambda/aws-nodejs-dev-goodbye",
        "RoleArn": {
          "$ref": "$[\"Resources\"][\"HelloSubscriptionFilter\"][\"Properties\"][\"RoleArn\"]"
        }
      },
      "DependsOn": [
        "GoodbyeLogGroup"
      ]
    }
```
