### ISSUE TITLE
Getting error: Requested attribute arn does not exist in schema for AWS::Lambda::Function

### ISSUE THREAD

**Issue by petebachant** [dougmoscrop/serverless-plugin-log-subscription#68]
Getting this issue when attempting to deploy:

```
CREATE_FAILED: CreateReportSubscriptionFilter (AWS::Logs::SubscriptionFilter)
Requested attribute arn does not exist in schema for AWS::Lambda::Function
```

Maybe worth noting that the Lambda whose ARN it fails to find changes, seemingly randomly.

My config looks something like:

```yaml
custom:
  logSubscription:
    enabled: true
    destinationArn:
      Fn::GetAtt: ["SendErrorMessageToSlackLambdaFunction", "arn"]
    filterPattern: ERROR
    addLambdaPermission: true

functions:
  createReport:
    timeout: 900
    image:
      name: ${opt:stage}
      command: app.create_report
    environment: ${file(./sls/python-function-env.yml):${opt:stage}}

  sendErrorMessageToSlack:
    image:
      name: ${opt:stage}
      command: app.send_error_message_to_slack
    environment: ${file(./sls/python-function-env.yml):${opt:stage}}
    logSubscription: false
```

Edit: Turns out the issue was using "arn" instead of "Arn" in the `GetAtt` call. My mistake!
