### ISSUE TITLE
[Feature] - Set api gateway destination arn separately from lambda destination arn

### ISSUE THREAD

**Issue by codezninja** [dougmoscrop/serverless-plugin-log-subscription#82]
The parsing of logs between lambda and api gateway can be different. Would it be possible to set the destination arn for api gateway logs to to have a different value instead?

ie

```yaml
custom:
  logSubscription:
    enabled: true
    destinationArn: arn:aws:logs:${self:provider.region}:xxxxxxxxx:destination:xxxxxxxxx-cloudwatch-lambda-destination-${self:provider.region}
    apiGatewayLogs:
      destinationArn: arn:aws:logs:${self:provider.region}:xxxxxxxxx:destination:xxxxxxxxx-cloudwatch-api-gateway-destination-${self:provider.region}
```
