### ISSUE TITLE
Custom function configuration is broken

### ISSUE THREAD

**Issue by ab-wave-rider** [dougmoscrop/serverless-plugin-log-subscription#83]
Using [serverless-plugin-log-subscription](https://github.com/dougmoscrop/serverless-plugin-log-subscription) version 2.2

Official documentation says:
Custom function settings:

```
custom:
  logSubscription:
    destinationArn: 'some-arn'

functions:
  myFunction:
    logSubscription:
      filterPattern: 'WARN*'
```

But adding `    logSubscription:
      filterPattern: 'WARN*'` to function does't work.

SLS outputs an error:
`Warning: Invalid configuration encountered
  at 'functions.ingest.logSubscription': must be boolean
Learn more about configuration validation here: http://slss.io/configuration-validation`

And cloudwatch subscription filter end up being w/o name or filter pattern.
